name: Build and Deploy React

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Deploy to Server
        run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} 'rm -rf $HOME/pipeline-app && mkdir -p $HOME/pipeline-app && cd $HOME/pipeline-app && git clone https://github.com/tuantranquang20/pipeline-app.git . && chmod +x deploy.sh && ./deploy.sh'
