name: Build and Deploy React

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use SSH key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ env.SSH_KEY }}
    - name: Deploy to Server
      run: ssh ${{env.SSH_USER}}@${{env.SSH_HOST}} 'bash -s' < ./../deploy.sh
      
