name: Build and Deploy React

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      SOURCE_DIR: "build/"

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy production
        if: github.ref == 'refs/heads/master'
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          remote: ${{ secrets.HOME_PATH }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}