name: Build and Deploy React

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install SSH
      run: sudo apt-get install openssh-client

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
            rm -rf $HOME/pipeline-app
            mkdir -p $HOME/pipeline-app
            cd $HOME/pipeline-app
            git clone https://github.com/tuantranquang20/pipeline-app.git .
            chmod +x deploy.sh
            ./deploy.sh
      
